### ISSUE TITLE
你好，这个模型可以选择不同的输入形态，输出形态

### ISSUE THREAD

**Issue by seeyourcell** [VITA-MLLM/VITA#13]
你好，这个模型可以选择不同的输入形态，输出形态？
比如
text   ->  video

text +video -> image

text + audio -> text

text+ audio + image -> image +text

等等这样的形势

**Comment by BradyFU** [comment]
Hi, 感谢关注。
text -> text
audio -> text
image/video + text/audio -> text

目前不支持生成图像。
其他形式跟训练数据强相关，有对应训练数据的话该框架可以支持。
