### ISSUE TITLE
问一下哈，代码还开源么

### ISSUE THREAD

**Issue by stanpcf** [VITA-MLLM/VITA#17]

**Comment by zhongJY1998** [comment]
同问

**Comment by BradyFU** [comment]
Hi, thanks for your attention. We will open source the code and weights tomorrow. 
Long wait!

**Comment by plancktree** [comment]
> Hi, thanks for your attention. We will open source the code and weights tomorrow. Long wait!

2024.9.5?

**Comment by BradyFU** [comment]
The night of Sep. 5th or the early hours of Sep. 6. We are conducting final checks and verification.

**Comment by plancktree** [comment]
> The night of Sep. 5th or the early hours of Sep. 6th We are conducting final checks and verification.

great
