### ISSUE TITLE
How to finetune?

### ISSUE THREAD

**Issue by kike-0304** [VITA-MLLM/VITA#18]

**Comment by BradyFU** [comment]
https://github.com/VITA-MLLM/VITA?tab=readme-ov-file#continual-training

**Comment by kike-0304** [comment]
> https://github.com/VITA-MLLM/VITA?tab=readme-ov-file#continual-training
How to add text input？
"conversations": [
            {
                "from": "human",
                "value": "<image>\n<audio>\n"
            }

is：
"conversations": [
            {
                "from": "human",
                "value": "What do you see happening in this image?\n<image>\n<audio>\n"
            }？

**Comment by linhaojia13** [comment]
@kike-0304 Could you please describe your issue in more detail?
