### ISSUE TITLE
Typo in arXiv paper

### ISSUE THREAD

**Issue by Bili-Sakura** [VITA-MLLM/VITA#2]
A minor typo in [VITA: Towards open-source interactive omni multimodal LLM](http://arxiv.org/pdf/2408.05211)

Original:

```markdown
[40] OpenAI. Hello gpt-4o. 2023.
```

Corrected:
```markdown
[40] OpenAI. Hello gpt-4o. 2024.
```

**Comment by BradyFU** [comment]
Hi, thank you very much!
