### ISSUE TITLE
ValueError: limit_mm_per_prompt is only supported for multimodal models.

### ISSUE THREAD

**Issue by MeinhardZhou** [VITA-MLLM/VITA#22]
when run `python -m web_demo.web_ability_demo  demo_VITA_ckpt/`

it displays `ValueError: limit_mm_per_prompt is only supported for multimodal models.`
![image](https://github.com/user-attachments/assets/41ec11dc-811f-4984-8046-7a2b49dd6510)

what can i do to solve this? do something in vllm?

**Environment:**
![image](https://github.com/user-attachments/assets/1d61a185-5594-4e91-b8a6-9ac65c02110c)

**Comment by longzw1997** [comment]
Have you made sure to overwrite the files from vllm_tools to the correct location? For instance, after properly overwriting, the contents inside demo_VITA_ckpt/ should look like this.
![231725673972_ pic](https://github.com/user-attachments/assets/caf59a74-4dd0-45ea-be42-4e17ae69eb0c)

**Comment by MeinhardZhou** [comment]
I found something lacking in `your_anaconda/envs/vita_demo/lib/python3.10/site-packages/vllm/model_executor/models/`
