### ISSUE TITLE
Error while running python -m web_demo.web_ability_demo  demo_VITA_ckpt/

### ISSUE THREAD

**Issue by sambalshikhar** [VITA-MLLM/VITA#23]
![image](https://github.com/user-attachments/assets/e3456854-ad8f-42dd-b39b-d01ee9cba7e5)

 File "/home/sahal.mullappilly/miniconda3/envs/vita_demo/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 926, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.configuration_mixtral_multimodal.MixtralMultiModalConfig'> to build an AutoTokenizer.

**Comment by longzw1997** [comment]
You can refer to [ issue#22](https://github.com/VITA-MLLM/VITA/issues/22) to confirm whether the files in vllm_tools have been correctly overwritten in the appropriate folder.

**Comment by sambalshikhar** [comment]
Yes all the three files [__init__.py ,mixtral.py,whale.py] are already present

**Comment by MeinhardZhou** [comment]
same error.
![image](https://github.com/user-attachments/assets/46b4037f-3d67-4920-8fb2-60d32c6ac5ed)
![image](https://github.com/user-attachments/assets/7575750d-4dc5-4acb-800e-72c845396ee1)

![image](https://github.com/user-attachments/assets/6b507378-121b-4cae-811d-bf375658ef8c)

![image](https://github.com/user-attachments/assets/eb476cd6-1ab2-4bb8-a2cc-50b8874cdca9)

**Comment by MeinhardZhou** [comment]
> ![WeChatc39cd69c9f5df76dc487d64befb40dc1](https://private-user-images.githubusercontent.com/85285159/366477668-6fb7b99b-c538-448b-8eef-1f1befe03902.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjUyMzksIm5iZiI6MTcyNjIyNDkzOSwicGF0aCI6Ii84NTI4NTE1OS8zNjY0Nzc2NjgtNmZiN2I5OWItYzUzOC00NDhiLThlZWYtMWYxYmVmZTAzOTAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEwNTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZGI5ZWE3NzBlMDM0NGI2NmUwMmE0MDY4YTA3NzE3MWE2MTM1ZDM1Njg0YTU1ZTBhNWUxODY0OTVhMGY0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v1TbJdsruiZ2ZRNcaSwtVzWo14cOtbmfuBA5Zm400f4) In our tests, it loads correctly here. Could you provide more information? For example, the contents of your folder, your environment, etc.

I found that there is no such path in my environment.
`/root/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/transformers_utils/tokenizer.py`

**Comment by longzw1997** [comment]
You can try the solution for [#issue28](https://github.com/VITA-MLLM/VITA/issues/28), such as changing cp -r to cp -rL.
