### ISSUE TITLE
Inconsistent results of VideoMME between github repo and tech report

### ISSUE THREAD

**Issue by QAQdev** [VITA-MLLM/VITA#24]
<img width="981" alt="image" src="https://github.com/user-attachments/assets/490c2ef3-9487-49ec-be7b-8275c7f7201d">

In the tech report fig. 5, shown above, VITA achieves 57.6% on VideoMME
![image](https://github.com/user-attachments/assets/87e169ab-fc4b-4c7c-a4d8-7e1bb8424ade)

In the Github repo figure, VITA achieves 59.2% on VideoMME

Could you please check which result is correct? Thanks!

**Comment by BradyFU** [comment]
Hi, thanks for your attention. The tech repo has been updated. Thank you!

**Comment by QAQdev** [comment]
> Hi, thanks for your attention. The tech repo has been updated. Thank you!

Does that mean I should conform to the result in the github repo?

**Comment by BradyFU** [comment]
yes
