### ISSUE TITLE
VideoMME Evaluation Setting

### ISSUE THREAD

**Issue by QAQdev** [VITA-MLLM/VITA#26]
Hello, thanks for your work!

I am reproducing VITA on VideoMME, I want to know what setting did you use for VideoMME, such as `max_frames`, `video_framerate`? @BradyFU 

Thanks again!

**Comment by linhaojia13** [comment]
> Hello, thanks for your work!
> 
> I am reproducing VITA on VideoMME, I want to know what setting did you use for VideoMME, such as `max_frames`, `video_framerate`? @BradyFU
> 
> Thanks again!

`max_frames = 32` and `video_framerate = 1`

A suggestion for speeding up Video-MME testing: you could extract frames from the video and save them as images on the hard drive. Then, during testing, you can just load the specific frames you need.

**Comment by QAQdev** [comment]
Thanks!
