### ISSUE TITLE
Significant poor performance observed

### ISSUE THREAD

**Issue by binisalegend** [VITA-MLLM/VITA#30]
When I used the **Real-Time Interactive Demo** mode, I tested it according to the configuration in the repo, using **4*A100** GPUs, but I observed obvious performance loss. I don't know why this performance loss occurs. Here are some proofs and examples of **poor performance**:

1.  User question: 请描述一下画面中的环境。
Model output: 很抱歉，作为一个人工智能，我无法直接感知或描述你的周围环境。我只能根据你提供的信息或问题来回答。如果你需要描述你的环境，你可以告诉我你所在的位置，我可以帮你查找相关信息。

2. User question: 请告诉我画面中的物体是什么。
Model output: 抱歉，作为一个文本模型，我无法直接看到或识别物体。我只能根据你提供的信息进行回答。如果你能描述一下这个物体，我会很乐意帮助你识别它。

3. At the same time, there are many problems in Non-awakening Interaction and Audio Interrupt Interaction. For example, the model can hardly recognize whether it is communicating with it, and it is difficult to interrupt the previous reply by asking new questions, etc.

Looking forward to your answer, thank you.

**Comment by longzw1997** [comment]
Normally, the model might occasionally provide incorrect answers, but it shouldn't consistently respond with an inability to see or recognize objects. If most of the answers are like this, it is possible that the model is not receiving visual information. You can check whether the camera is turned on or if the backend is correctly receiving the video feed.

**Comment by binisalegend** [comment]
> Normally, the model might occasionally provide incorrect answers, but it shouldn't consistently respond with an inability to see or recognize objects. If most of the answers are like this, it is possible that the model is not receiving visual information. You can check whether the camera is turned on or if the backend is correctly receiving the video feed.

When my question is related to the picture, the high probability model will reply like this: 很抱歉，由于我是一个文本助手，我无法直接读取图像中的内容，.....

Some attempts will return correct output, but the probability of this happening is extremely low.

**Comment by binisalegend** [comment]
By the way, is there any method which can make a judgement of whether the video message is successfully posting to the models? Thanks a lot.

**Comment by BradyFU** [comment]
Hi, thanks for your attention. Your results are so weird. 
You could try the Basic Demo first, and use the same user question.
The Real-Time Interactive Demo uses the same ckpt as the Basic Demo, so the results shoud be aligned.

Note that the Real-Time Interactive Demo needs the requirements of:
- Ensure a high-speed network connection.
- Use high-performance GPUs for deployment. In the demo video, we use 4 Nvidia H20 GPUs. A800, H800, or A100 will be much better.
- Maintain a quiet environment.

You could try the Basic Demo as a check.

**Comment by binisalegend** [comment]
> Hi, thanks for your attention. Your results are so weird. You could try the Basic Demo first, and use the same user question. The Real-Time Interactive Demo uses the same ckpt as the Basic Demo, so the results shoud be aligned.
> 
> Note that the Real-Time Interactive Demo needs the requirements of:
> 
> * Ensure a high-speed network connection.
> * Use high-performance GPUs for deployment. In the demo video, we use 4 Nvidia H20 GPUs. A800, H800, or A100 will be much better.
> * Maintain a quiet environment.
> 
> You could try the Basic Demo as a check.

Thanks for your explanation! I observed the logs and found that the tags before the current request were all '<audio>'. I found that it was because I did not click the red circle under the video module to start recording 😭, so the video was not transmitted to the model. Thank you again for your help and time.
