### ISSUE TITLE
out of memory when running demo via "python -m web_demo.web_ability_demo demo_VITA_ckpt/

### ISSUE THREAD

**Issue by future911** [VITA-MLLM/VITA#33]
您好，执行启动 demo： python - m web_demo. web_ability_demo/data/models/vita/VITA/demo_VITA_ckpt/
提示内存资源不足，具体 cuda 、gpu及报错情况如下：
The CUDA version is 12.2.
vllm 0.5.5
vllm-flash-attn 2.6.1

gpu：8*v100 32G
![image](https://github.com/user-attachments/assets/8bfd379d-08d6-464c-8147-7265c2815649)

![image](https://github.com/user-attachments/assets/5152a5c9-8724-4b9a-b13d-b18926bf565f)
![image](https://github.com/user-attachments/assets/99203670-4c8d-4d05-bfa6-382453f1ff84)

Thanks！

**Comment by longzw1997** [comment]
If you have 8*v100 32G, you can try setting tensor_parallel_size=8 on [line 343](https://github.com/VITA-MLLM/VITA/blob/main/web_demo/web_ability_demo.py).

**Comment by future911** [comment]
问题已解决，多谢
