### ISSUE TITLE
无法连接摄像头，并且页面提示找不到麦克风

### ISSUE THREAD

**Issue by future911** [VITA-MLLM/VITA#34]
您好，已经成功登录 vita，但是 vita 页面点击访问摄像头，提示无法访问摄像头，另外页面显示找不到麦克风，请问如何解决呢？

![image](https://github.com/user-attachments/assets/28cd3177-7f9a-4d9c-92f7-5354612158f4)

感谢！

**Comment by lc222** [comment]
想问下是如何解决的，我看了浏览器设置，开了摄像头权限也不行

**Comment by lc222** [comment]
@future911

**Comment by zhongJY1998** [comment]
同问

**Comment by BradyFU** [comment]
#39 
请参考这个，有问题再联系~
