### ISSUE TITLE
无法访问摄像头和麦克风

### ISSUE THREAD

**Issue by zhongJY1998** [VITA-MLLM/VITA#39]
<img width="958" alt="1" src="https://github.com/user-attachments/assets/f7784151-fa42-4195-8137-c21901ae8d57">
<img width="956" alt="2" src="https://github.com/user-attachments/assets/f107b741-c55f-4ba2-8404-8aa57a30fb42">
<img width="339" alt="3" src="https://github.com/user-attachments/assets/cf23b7a4-7e1b-467d-b800-0543d6531ed4">
<img width="342" alt="4" src="https://github.com/user-attachments/assets/845fdb54-a29b-4bd7-b1ad-48de25f23efa">
请问一下,这是什么原因额

**Comment by BradyFU** [comment]
1. 浏览器窗口输入：chrome://flags/#unsafely-treat-insecure-origin-as-secure

2. Insecure origins treated as secure中输入远程demo访问的ip地址

3. 启用Insecure origins treated as secure

4. 重启浏览器

**Comment by zhongJY1998** [comment]
谢谢

**Comment by BradyFU** [comment]
不客气，欢迎群里加我微信（群主），有问题随时联系。
