### ISSUE TITLE
关于状态<2>的问题

### ISSUE THREAD

**Issue by liyunlongaaa** [VITA-MLLM/VITA#40]
您好，模型训练过程中是有数据告知<2>为噪声，模型不应该响应输出终止(训练时防止性能下降还是正常用回答训）。但是我不理解的是，模型在推理时，模型如何判断哪段语音属于<2>噪声呢？比如一个人在提问，另一个声音可能是他妈妈喊他吃饭，喊吃饭应该会标记为噪音，模型怎么完成这个标记并无视这段语音呢？谢谢

**Comment by BradyFU** [comment]
您好，感谢关注！
模型推理和训练是强相关的，训练中我们标记哪种case属于噪声语音，推理时就会有对应倾向。
目前，我们初步验证了噪声语音这条技术方案是可行的，并且我们现阶段对于噪声语音的定义非常宽泛：宽泛的陈述句，比如“今天天气真好”。
但显然这个初步的宽泛设定在实际应用中会有不少问题。噪声语音是个很深的方向亟待继续开发，即根据实际真实场景详细收集整理噪声语音和非噪声语音，工作量会非常大。
你提到的是另一种语音问题，即两个人在同时讲话，这个又涉及到语音的分离，这可能需要靠前置的环节来解决，或者也集这类真实的语音数据，用于根据实际需求是否标记为噪声语音，依靠我们的方案用于训练。

**Comment by liyunlongaaa** [comment]
很棒的工作，十分感谢回答^O^。



---原始邮件---
发件人: "Chaoyou ***@***.***&gt;
发送时间: 2024年9月15日(周日) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VITA-MLLM/VITA] 关于状态<2&gt;的问题 (Issue #40)




 
您好，感谢关注！
 模型推理和训练是强相关的，训练中我们标记哪种case属于噪声语音，推理时就会有对应倾向。
 目前，我们初步验证了噪声语音这条技术方案是可行的，并且我们现阶段对于噪声语音的定义非常宽泛：宽泛的陈述句，比如“今天天气真好”。
 但显然这个初步的宽泛设定在实际应用中会有不少问题。噪声语音是个很深的方向亟待继续开发，即根据实际真实场景详细收集整理噪声语音和非噪声语音，工作量会非常大。
 你提到的是另一种语音问题，即两个人在同时讲话，这个又涉及到语音的分离，这可能需要靠前置的环节来解决，或者也集这类真实的语音数据，用于根据实际需求是否标记为噪声语音，依靠我们的方案用于训练。

**Comment by BradyFU** [comment]
客气了~
