### ISSUE TITLE
"RuntimeError: CUDA error: an illegal memory access was encountered" when running web_ability_demo

### ISSUE THREAD

**Issue by superobk** [VITA-MLLM/VITA#41]
I have 4*80 machine, and change the “tensor_parallel_size = 4”, but the RuntimeError will happen, any idea to resolve the problem, should I change any other parameters? Thank you!

> 
python3 -m web_demo.web_ability_demo  demo_VITA_ckpt/
WARNING 09-15 15:01:09 config.py:1563] Casting torch.bfloat16 to torch.float16.
INFO 09-15 15:01:09 config.py:813] Defaulting to use mp for distributed inference
INFO 09-15 15:01:09 llm_engine.py:184] Initializing an LLM engine (v0.5.5) with config: model='demo_VITA_ckpt/', speculative_config=None, tokenizer='demo_VITA_ckpt/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, **tensor_parallel_size=4, pipeline_parallel_size=1**, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=demo_VITA_ckpt/, use_v2_block_manager=False, enable_prefix_caching=False)
WARNING 09-15 15:01:09 multiproc_gpu_executor.py:59] **Reducing Torch parallelism from 36 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.**
INFO 09-15 15:01:09 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=54558) INFO 09-15 15:01:10 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=54559) INFO 09-15 15:01:10 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=54560) INFO 09-15 15:01:10 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 09-15 15:01:10 utils.py:975] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=54559) INFO 09-15 15:01:10 utils.py:975] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=54558) INFO 09-15 15:01:10 utils.py:975] Found nccl from library libnccl.so.2
INFO 09-15 15:01:10 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=54559) INFO 09-15 15:01:10 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=54560) INFO 09-15 15:01:10 utils.py:975] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=54558) INFO 09-15 15:01:10 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=54560) INFO 09-15 15:01:10 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 09-15 15:01:11 shm_broadcast.py:235] **vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7fb617c13df0>, local_subscribe_port=43841, remote_subscribe_port=None)**
INFO 09-15 15:01:11 model_runner.py:879] Starting to load model demo_VITA_ckpt/...
(VllmWorkerProcess pid=54559) INFO 09-15 15:01:11 model_runner.py:879] Starting to load model demo_VITA_ckpt/...
(VllmWorkerProcess pid=54558) INFO 09-15 15:01:11 model_runner.py:879] Starting to load model demo_VITA_ckpt/...
(VllmWorkerProcess pid=54560) INFO 09-15 15:01:11 model_runner.py:879] Starting to load model demo_VITA_ckpt/...
Loading safetensors checkpoint shards:   0% Completed | 0/20 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   5% Completed | 1/20 [00:01<00:33,  1.74s/it]
Loading safetensors checkpoint shards:  10% Completed | 2/20 [00:03<00:30,  1.72s/it]
Loading safetensors checkpoint shards:  15% Completed | 3/20 [00:05<00:28,  1.70s/it]
Loading safetensors checkpoint shards:  20% Completed | 4/20 [00:06<00:27,  1.69s/it]
Loading safetensors checkpoint shards:  25% Completed | 5/20 [00:08<00:25,  1.70s/it]
Loading safetensors checkpoint shards:  30% Completed | 6/20 [00:10<00:23,  1.71s/it]
Loading safetensors checkpoint shards:  35% Completed | 7/20 [00:11<00:22,  1.72s/it]
Loading safetensors checkpoint shards:  40% Completed | 8/20 [00:13<00:20,  1.73s/it]
Loading safetensors checkpoint shards:  45% Completed | 9/20 [00:15<00:18,  1.71s/it]
Loading safetensors checkpoint shards:  50% Completed | 10/20 [00:17<00:17,  1.71s/it]
Loading safetensors checkpoint shards:  55% Completed | 11/20 [00:18<00:15,  1.70s/it]
Loading safetensors checkpoint shards:  60% Completed | 12/20 [00:20<00:13,  1.68s/it]
Loading safetensors checkpoint shards:  65% Completed | 13/20 [00:22<00:11,  1.67s/it]
Loading safetensors checkpoint shards:  70% Completed | 14/20 [00:23<00:09,  1.66s/it]
Loading safetensors checkpoint shards:  75% Completed | 15/20 [00:25<00:08,  1.63s/it]
Loading safetensors checkpoint shards:  80% Completed | 16/20 [00:26<00:06,  1.63s/it]
Loading safetensors checkpoint shards:  85% Completed | 17/20 [00:27<00:04,  1.34s/it]
Loading safetensors checkpoint shards:  90% Completed | 18/20 [00:29<00:02,  1.41s/it]
(VllmWorkerProcess pid=54559) Uninitialized parameters: ['model.audio_encoder.encoder.global_cmvn.istd', 'model.audio_encoder.encoder.global_cmvn.mean']
(VllmWorkerProcess pid=54559) INFO 09-15 15:01:41 model_runner.py:890] Loading model weights took 22.6129 GB
Loading safetensors checkpoint shards:  95% Completed | 19/20 [00:30<00:01,  1.45s/it]
Loading safetensors checkpoint shards: 100% Completed | 20/20 [00:32<00:00,  1.58s/it]
Loading safetensors checkpoint shards: 100% Completed | 20/20 [00:32<00:00,  1.63s/it]

Uninitialized parameters: ['model.audio_encoder.encoder.global_cmvn.istd', 'model.audio_encoder.encoder.global_cmvn.mean']
INFO 09-15 15:01:44 model_runner.py:890] **Loading model weights took 22.6129 GB**
(VllmWorkerProcess pid=54558) Uninitialized parameters: ['model.audio_encoder.encoder.global_cmvn.istd', 'model.audio_encoder.encoder.global_cmvn.mean']
(VllmWorkerProcess pid=54558) INFO 09-15 15:01:45 model_runner.py:890] Loading model weights took 22.6129 GB
(VllmWorkerProcess pid=54560) Uninitialized parameters: ['model.audio_encoder.encoder.global_cmvn.istd', 'model.audio_encoder.encoder.global_cmvn.mean']
(VllmWorkerProcess pid=54560) INFO 09-15 15:01:46 model_runner.py:890] Loading model weights took 22.6129 GB
(VllmWorkerProcess pid=54558) WARNING 09-15 15:01:46 model_runner.py:1057] **Computed max_num_seqs (min(256, 32768 // 903168)) to be less than 1. Setting it to the minimum value of 1.**
WARNING 09-15 15:01:46 model_runner.py:1057] Computed max_num_seqs (min(256, 32768 // 903168)) to be less than 1. Setting it to the minimum value of 1.
(VllmWorkerProcess pid=54559) WARNING 09-15 15:01:46 model_runner.py:1057] Computed max_num_seqs (min(256, 32768 // 903168)) to be less than 1. Setting it to the minimum value of 1.
(VllmWorkerProcess pid=54560) WARNING 09-15 15:01:46 model_runner.py:1057] Computed max_num_seqs (min(256, 32768 // 903168)) to be less than 1. Setting it to the minimum value of 1.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/VITA/web_demo/web_ability_demo.py", line 361, in <module>
[rank0]:     main(args.model_path)
[rank0]:   File "/home/VITA/web_demo/web_ability_demo.py", line 340, in main
[rank0]:     llm = LLM(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 175, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 473, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 284, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 390, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 38, in determine_num_available_blocks
[rank0]:     num_blocks = self._run_workers("determine_num_available_blocks", )
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/worker/worker.py", line 222, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1097, in profile_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1415, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 1165, in forward
[rank0]:     hidden_states = self.language_model(input_ids,
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 619, in forward
[rank0]:     hidden_states, residual = layer(positions, hidden_states,
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 555, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 501, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/attention/layer.py", line 98, in forward
[rank0]:     return self.impl.forward(query,
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/attention/backends/flash_attn.py", line 671, in forward
[rank0]:     out = torch.ops.vllm.flash_attn_varlen_func(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/_ops.py", line 1061, in __call__
[rank0]:     return self_._op(*args, **(kwargs or {}))
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 236, in backend_impl
[rank0]:     result = self._backend_fns[device_type](*args, **kwargs)
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm/attention/backends/flash_attn.py", line 48, in flash_attn_varlen_func
[rank0]:     return _flash_attn_varlen_func(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 1154, in flash_attn_varlen_func
[rank0]:     return FlashAttnVarlenFunc.apply(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 632, in forward
[rank0]:     out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
[rank0]:   File "/data/anaconda3/envs/vita_demo/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 90, in _flash_attn_varlen_forward
[rank0]:     out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
[rank0]: **RuntimeError: CUDA error: an illegal memory access was encountered**
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR 09-15 15:01:53 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 54558 died, exit code: -15
INFO 09-15 15:01:53 multiproc_worker_utils.py:123] Killing local vLLM worker processes
/data/anaconda3/envs/vita_demo/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

>

**Comment by superobk** [comment]
Just double check, seems vllm could not load 4 GPU entity even I configured the “tensor_parallel_size=4”

![image](https://github.com/user-attachments/assets/d96ddeb3-e53d-47eb-86b1-f422c76cd843)

My vllm and flash_attn version are as below:
(vita_demo) [root@localhost VITA]# pip list | grep vllm
vllm                              0.5.5
vllm-flash-attn                   2.6.1

It is aligned with web demo requirements. Please kindly assist if you find any hint. Thanks!

**Comment by longzw1997** [comment]
It might be an environment issue, as no similar problems have been found so far.

**Comment by superobk** [comment]
> It might be an environment issue, as no similar problems have been found so far.

It is weird that I deploy the python package in 2 environments, but both have similar issues.
Anyway, thanks for the assistance!

**Comment by LiuMY13** [comment]
same to me for web_interactive_demo

**Comment by Anonymous4CV** [comment]
I meet the same problem. Did you find any solution?
