### ISSUE TITLE
请问下是否支持输入是语音，输出是语音的形式？

### ISSUE THREAD

**Issue by learn01one** [VITA-MLLM/VITA#46]
你好，请问下是否支持输入是语音，输出是语音的形式？现在是输出只能文字吗，谢谢～

**Comment by BradyFU** [comment]
目前输出可以文字转TTS。下个版本支持直接输出语音，欢迎关注！

**Comment by learn01one** [comment]
> 目前输出可以文字转TTS。下个版本支持直接输出语音，欢迎关注！

期待～有计划预计什么时候么
