### ISSUE TITLE
How many GPUs are needed to train this model?

### ISSUE THREAD

**Issue by ys-zong** [VITA-MLLM/VITA#5]
Hi, thanks for the great work! I wonder how many GPUs and how many hours/days are needed for training in each stage?

**Comment by BradyFU** [comment]
Hi, if you have four A800, it can be trained in one week (2+5 days).

**Comment by BradyFU** [comment]
Four A800, and each has 8 GPUs.

**Comment by zte-tcb** [comment]
hello, 

> Hi, if you have four A800, it can be trained in one week (2+5 days).

这个是对齐训练训两天，connectors +Mixtral 8×7B训练训5天？
