### ISSUE TITLE
audio_processor error：cannot open q1.wav!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by sankexin** [VITA-MLLM/VITA#50]
CUDA_VISIBLE_DEVICES=0,1 python video_audio_demo.py --model_path VITA/VITA_ckpt --image_path asset/vita_log2.png --model_type mixtral-8x7b --conv_mode mixtral_two --audio_path asset/q1.wav

cannot open q1.wav!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/home/VITA/video_audio_demo.py", line 182, in <module>
    audio, audio_for_llm_lens = audio_processor.process(os.path.join(audio_path))
  File "/home/VITA/vita/model/multimodal_encoder/whale/init_model.py", line 40, in process
    if sample_rate != self.dataset_conf["resample_conf"]["resample_rate"]:
UnboundLocalError: local variable 'sample_rate' referenced before assignment

there is something wrong with audio_encoder.

**Comment by linhaojia13** [comment]
The issue is likely with `self.dataset_conf`. You can start tracing the problem from this variable.

**Comment by sankexin** [comment]
> audio, audio_for_llm_lens = audio_processor.process(os.path.join(audio_path))
 
The file "asset/q1.wav" exists and is a normal file，

**Comment by sankexin** [comment]
> The issue is likely with `self.dataset_conf`. You can start tracing the problem from this variable.

> audio, audio_for_llm_lens = audio_processor.process(os.path.join(audio_path))
 
The file "asset/q1.wav" exists and is a normal file，it can get dataset，
The audio pretraining weights can be read normally,
 but when the files and weights enter the model, an error occurs, indicating a bug in the open source code.

**Comment by sankexin** [comment]
> The issue is likely with `self.dataset_conf`. You can start tracing the problem from this variable.

> audio, audio_for_llm_lens = audio_processor.process(os.path.join(audio_path))
 
I have tried, The file "asset/q1.wav" exists and is a normal file，it can get dataset，
The audio pretraining weights can be read normally,
 but when the files and weights enter the model, an error occurs, indicating a bug in the open source code.

could you Reproduce this .wav infer problem ,or anything bug in device ?

**Comment by sankexin** [comment]
torchaudio on my device can not read .wav，it is the problem of my device，I will try, continue.

**Comment by sankexin** [comment]
modify：VITA/video_audio_demo.py

import soundfile as sf
audio, audio_for_llm_lens = audio_processor.process(os.path.join(audio_path))
# audio, fs = sf.read(os.path.join(audio_path))
# audio = torch.tensor(audio, dtype=torch.float16).unsqueeze(0)

**Comment by sankexin** [comment]
use ffmpeg-4.4.4 can use torchaudio read .wav
```
apt-get update
apt-get upgrade -y

apt-get install -y libmad0 libmad0-dev libid3tag0 libid3tag0-dev libmp3lame-dev libflac-dev libvorbis-dev yasm nasm

wget --no-check-certificate https://www.ffmpeg.org/releases/ffmpeg-4.4.4.tar.gz
tar xzf ffmpeg-4.4.4.tar.gz
cd ffmpeg-4.4.4
./configure --enable-shared --enable-libmp3lame
make -j32
make install
cd -

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

**Comment by Eureka-Maggie** [comment]
sudo apt-get install ffmpeg
