### ISSUE TITLE
VITA 1.5 在线demo 报错

### ISSUE THREAD

**Issue by lwj2001** [VITA-MLLM/VITA#64]
```
ValueError: Trying to set a tensor of shape torch.Size([51760, 4096]) in "weight" (which has shape torch.Size([152064, 4096])), this looks incorrect.
```

**Comment by muchen2019** [comment]
I also meet see problem.

**Comment by shawnleolxy** [comment]
Thank you for your interest in this project. It seems that the model is not configured correctly. Could you provide more error information for us to troubleshoot?

**Comment by lwj2001** [comment]
是我搞错了，把1.0 和 1.5 的ckpt搞混了
