### ISSUE TITLE
Quesetion of Real-time demo of VITA-1.5.

### ISSUE THREAD

**Issue by muchen2019** [VITA-MLLM/VITA#68]
Glad to see your nice work VITA-1.5. As can be seen in demo video, VITA 1.5 shows a powerful ability in real-time interation. However, I meet one question. When I reproduce the interactive demo, it seems to not respond well to voice and cannot be interrupted by new voice during the TTS stage.  Therefore, i want to ask whether the "server.py" demo is the published version of video demo. If not, can you help me to improve it. What's more, the discussion group is invalid. Thanks!

**Comment by longzw1997** [comment]
What do you mean by the TTS cannot be interrupted by new speech? Does it mean that the TTS output does not stop immediately after the new speech is finished, or does it seem that the model did not receive the new input speech?

**Comment by muchen2019** [comment]
1. Hi, thanks for your reply. Maybe I do not describe the problem clearly. In specifically, I run the server demo of VITA 1.5 and the running status is shown in the picture. It should be noted that I open the the dialogue and video functions. However, when I started the dialogue, the demo seemes unable to detect or respond to the audio content (I have configured VAD files in source/ and opened audio and video permissions.). 2. Regarding the interruption of TTS, I have seen related functions in VITA 1.5, but I have not been able to fully test it yet because I cannot reproduce the results in the demo video. But in VITA 1.0, interruptions in the TTS generation process seem to be unresponsive. Sincerely hope that you can help me solve the audio detection and response issues of VITA 1.5 demo. Thank you.

**Comment by longzw1997** [comment]
In your picture, it appears that the VAD has successfully captured the audio and fed it into the input queue. You might consider printing the inputs and outputs of the model, as well as the inputs and outputs of the TTS, to better pinpoint where the issue might be.

**Comment by fromlimbo** [comment]
同样的问题
