### ISSUE TITLE
How did you synthesize the bilingual pure-text instruction tuning corpus?

### ISSUE THREAD

**Issue by david-leon** [VITA-MLLM/VITA#8]
Great work for LMM research!
In section 3.1 of the arxiv paper, it mentioned "we use 5 million synthetic bilingual corpus for pure-text instruction tuning." I'm quite curious about how you curated the SFT text corpus via synthesis method? Is it possible to share any clue?

**Comment by BradyFU** [comment]
Hi, thanks for your attention on our work. This part (about pure-text data) is hard to reveal. If it is convenient, you could leave your WeChat ID, we can open discussion.
